[phases.setup]
nixPkgs = ["nodejs", "npm"]

[phases.install]
cmds = ["npm install --no-audit --no-fund --include=dev"]

[phases.build]
cmds = ["CI=false npm run build"]

[start]
cmd = "npx serve -s build -l 3000" 