repos:
  # Базовые проверки
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
        description: "Удаление лишних пробелов в конце строк"
      - id: end-of-file-fixer
        description: "Проверка окончания файлов"
      - id: check-yaml
        description: "Проверка синтаксиса YAML файлов"
      - id: check-json
        description: "Проверка синтаксиса JSON файлов"
      - id: check-toml
        description: "Проверка синтаксиса TOML файлов"
      - id: check-merge-conflict
        description: "Проверка на конфликты слияния"
      - id: debug-statements
        description: "Проверка на отладочные операторы"

  # Black - форматирование кода
  - repo: https://github.com/psf/black
    rev: 23.11.0
    hooks:
      - id: black
        description: "Форматирование Python кода с помощью Black"
        language_version: python3
        args: [--line-length=88]

  # isort - сортировка импортов
  - repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
      - id: isort
        description: "Сортировка импортов с помощью isort"
        args: [--profile=black, --line-length=88]

  # flake8 - проверка стиля кода
  - repo: https://github.com/pycqa/flake8
    rev: 6.1.0
    hooks:
      - id: flake8
        description: "Проверка стиля кода с помощью flake8"
        args: [
          --max-line-length=88,
          --extend-ignore=E203,W503,E501
        ]

  # mypy - проверка типов
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.7.1
    hooks:
      - id: mypy
        description: "Проверка типов с помощью mypy"
        additional_dependencies: [
          types-requests,
          types-redis,
          types-python-dateutil
        ]
        args: [--ignore-missing-imports]

  # Проверка безопасности
  - repo: https://github.com/PyCQA/bandit
    rev: 1.7.5
    hooks:
      - id: bandit
        description: "Проверка безопасности кода"
        args: [-r, ., -f, json, -o, bandit-report.json]
        exclude: tests/

  # Проверка зависимостей
  - repo: https://github.com/Lucas-C/pre-commit-hooks-safety
    rev: v1.3.2
    hooks:
      - id: python-safety-dependencies-check
        description: "Проверка уязвимостей в зависимостях"

# Настройки
ci:
  autofix_commit_msg: |
    [pre-commit.ci] auto fixes from pre-commit.com hooks

    for more information, see https://pre-commit.ci
  autofix_prs: true
  autoupdate_branch: ''
  autoupdate_commit_msg: '[pre-commit.ci] pre-commit autoupdate'
  autoupdate_schedule: weekly
  skip: []
  submodules: false 